apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content 
  namespace: netology 
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Эта страница из ConfigMap подключенная к Deployment</title> 
    </head>
    <body>
      <h1>Привет от Задания 1!</h1>
    </body>
    </html>
