apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-backend
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-backend
    spec:
      containers:
        - name: {{ .Values.containers.backend.name }}
          image: {{ .Values.image.backend.repository }}
          imagePullPolicy: {{ .Values.image.backend.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containers.backend.port }}
          env:
            - name: HTTP_PORT
              value: {{ .Values.containers.backend.port | quote }}
            - name: MESSAGE
              value: "Hello from backend"
